<?php

namespace Database\Seeders;

use App\Models\Brand;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BrandSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $brands = [
            ['name' => 'CHI CHI', 'short_name' => 'CHI'],
            ['name' => '1880 CLUB', 'short_name' => '188'],
            ['name' => '7 FOR ALL MANKIND', 'short_name' => '7'],
            ['name' => 'A F WHITE', 'short_name' => 'AFW'],
            ['name' => 'ADIDAS', 'short_name' => 'ADI'],
            ['name' => 'AGATHA RUIZ DE LA PRADA', 'short_name' => 'AGA'],
            ['name' => 'AMACH', 'short_name' => 'AMA'],
            ['name' => 'ANATOMIC & CO', 'short_name' => 'ANA'],
            ['name' => 'ANY', 'short_name' => 'ANY'],
            ['name' => 'ARMANI EXCHANGE', 'short_name' => 'ARM'],
            ['name' => 'ARMOR-LUX', 'short_name' => 'ARL'],
            ['name' => 'ASSORTED', 'short_name' => 'ASS'],
            ['name' => 'ASST', 'short_name' => 'AST'],
            ['name' => 'AX PARIS', 'short_name' => 'AXP'],
            ['name' => 'AZOR', 'short_name' => 'AZO'],
            ['name' => 'BABYCHAM', 'short_name' => 'BAB'],
            ['name' => 'BANNER', 'short_name' => 'BAN'],
            ['name' => 'BARBOUR', 'short_name' => 'BAR'],
            ['name' => 'BARKER', 'short_name' => 'BAK'],
            ['name' => 'BASE LONDON', 'short_name' => 'BAS'],
            ['name' => 'BEAU BRUMMEL', 'short_name' => 'BEA'],
            ['name' => 'BELLA BAGS', 'short_name' => 'BEL'],
            ['name' => 'BEN SHERMAN', 'short_name' => 'BEN'],
            ['name' => 'BENCH', 'short_name' => 'BCH'],
            ['name' => 'BERGHAUS', 'short_name' => 'BER'],
            ['name' => 'BILLABONG', 'short_name' => 'BIL'],
            ['name' => 'BIRKENSTOCK', 'short_name' => 'BIR'],
            ['name' => 'BLINQ', 'short_name' => 'BLI'],
            ['name' => 'BLU FLOWERS', 'short_name' => 'BLU'],
            ['name' => 'BLUNDSTONE', 'short_name' => 'BLS'],
            ['name' => 'BOSS', 'short_name' => 'HUG'],
            ['name' => 'BRAVESOUL', 'short_name' => 'BRA'],
            ['name' => 'BRONX', 'short_name' => 'BRO'],
            ['name' => 'CALVIN KLEIN', 'short_name' => 'CAL'],
            ['name' => 'CAPRICE', 'short_name' => 'CAP'],
            ['name' => 'CARABEE', 'short_name' => 'CAB'],
            ['name' => 'CARHARTT WIP', 'short_name' => 'CAH'],
            ['name' => 'CARL GROSS', 'short_name' => 'CAG'],
            ['name' => 'CASHMINK', 'short_name' => 'CAS'],
            ['name' => 'CASIO', 'short_name' => 'CSI'],
            ['name' => 'CATERPILLAR', 'short_name' => 'CAT'],
            ['name' => 'CHAMPION', 'short_name' => 'CHA'],
            ['name' => 'CHEAP MONDAY', 'short_name' => 'CHE'],
            ['name' => 'CHERRAG', 'short_name' => 'CHR'],
            ['name' => 'CITY GODDESS', 'short_name' => 'CIT'],
            ['name' => 'CLAE', 'short_name' => 'CLE'],
            ['name' => 'CLARKS', 'short_name' => 'CLA'],
            ['name' => 'CLOSET', 'short_name' => 'CLO'],
            ['name' => 'COACH', 'short_name' => 'COA'],
            ['name' => 'COLORFUL STANDARD', 'short_name' => 'COL'],
            ['name' => 'CONCEPT FASHION', 'short_name' => 'CON'],
            ['name' => 'CONVERSE', 'short_name' => 'COV'],
            ['name' => 'CREP', 'short_name' => 'CRP'],
            ['name' => 'CREW CLOTHING', 'short_name' => 'CRE'],
            ['name' => 'CRIMINAL DAMAGE', 'short_name' => 'CRI'],
            ['name' => 'CROCS', 'short_name' => 'CRO'],
            ['name' => 'CUBA FOOTWEAR', 'short_name' => 'CUB'],
            ['name' => 'D.C. SHOE CO.', 'short_name' => 'DC'],
            ['name' => 'DADDYS MONEY', 'short_name' => 'DAD'],
            ['name' => 'DANCING LEOPARD', 'short_name' => 'DLE'],
            ['name' => 'DANIEL GRAHAME', 'short_name' => 'DAN'],
            ['name' => 'DARIO BELTRAN', 'short_name' => 'DAR'],
            ['name' => 'DAVID LUKE', 'short_name' => 'DAV'],
            ['name' => 'DEAD', 'short_name' => 'DED'],
            ['name' => 'DESIGUAL', 'short_name' => 'DES'],
            ['name' => 'DEUS', 'short_name' => 'DEU'],
            ['name' => 'DEVICE', 'short_name' => 'DEV'],
            ['name' => 'DGK', 'short_name' => 'DGK'],
            ['name' => 'DICKIES', 'short_name' => 'DIC'],
            ['name' => 'DIESEL', 'short_name' => 'DIE'],
            ['name' => 'DINO', 'short_name' => 'DIN'],
            ['name' => 'DKNY', 'short_name' => 'DKN'],
            ['name' => 'DOLCIS', 'short_name' => 'DOL'],
            ['name' => 'DOUGLAS & GRAHAME', 'short_name' => 'D&G'],
            ['name' => 'DR. MARTENS', 'short_name' => 'DR'],
            ['name' => 'DREW PEARSON', 'short_name' => 'DRW'],
            ['name' => 'DUCK & COVER', 'short_name' => 'DUC'],
            ['name' => 'DUNE', 'short_name' => 'DUE'],
            ['name' => 'DUNLOP', 'short_name' => 'DUN'],
            ['name' => 'DUTY', 'short_name' => 'DUT'],
            ['name' => 'EASTPAK', 'short_name' => 'EAS'],
            ['name' => 'ECCO', 'short_name' => 'ECC'],
            ['name' => 'EDC', 'short_name' => 'EDC'],
            ['name' => 'EDWIN', 'short_name' => 'EDW'],
            ['name' => 'ELEMENT', 'short_name' => 'ELE'],
            ['name' => 'ELISE RYAN', 'short_name' => 'ELI'],
            ['name' => 'ELLESSE', 'short_name' => 'ELL'],
            ['name' => 'EMIS', 'short_name' => 'EMI'],
            ['name' => 'ESCAPE', 'short_name' => 'ESC'],
            ['name' => 'ETNIES', 'short_name' => 'ETN'],
            ['name' => 'EURODA', 'short_name' => 'EUR'],
            ['name' => 'EUROPA', 'short_name' => 'ERO'],
            ['name' => 'EVISU', 'short_name' => 'EVI'],
            ['name' => 'EXIT', 'short_name' => 'EXI'],
            ['name' => 'FARAH', 'short_name' => 'FAR'],
            ['name' => 'FEELINGS', 'short_name' => 'FEE'],
            ['name' => 'FIRETRAP', 'short_name' => 'FIR'],
            ['name' => 'FITFLOP', 'short_name' => 'FIT'],
            ['name' => 'FLIRT', 'short_name' => 'FLI'],
            ['name' => 'FLY LONDON', 'short_name' => 'FLY'],
            ['name' => 'FOYLE COLLEGE', 'short_name' => 'FOY'],
            ['name' => 'FRANK WRIGHT', 'short_name' => 'FRA'],
            ['name' => 'FREAK', 'short_name' => 'FRK'],
            ['name' => 'FRED PERRY', 'short_name' => 'FRP'],
            ['name' => 'FREDDY', 'short_name' => 'FRD'],
            ['name' => 'FRENCH CONNECTION', 'short_name' => 'FRE'],
            ['name' => 'FROCK', 'short_name' => 'FRC'],
            ['name' => 'FRONT', 'short_name' => 'FRO'],
            ['name' => 'FRUIT OF THE LOOM', 'short_name' => 'FRU'],
            ['name' => 'G-STAR', 'short_name' => 'G-S'],
            ['name' => 'GANT', 'short_name' => 'GAN'],
            ['name' => 'GARVALIN', 'short_name' => 'GAR'],
            ['name' => 'GEOX', 'short_name' => 'GEO'],
            ['name' => 'GIANNI', 'short_name' => 'GIA'],
            ['name' => 'GIRL IN MIND', 'short_name' => 'GIM'],
            ['name' => 'GIRLS', 'short_name' => 'GIR'],
            ['name' => 'GLAMOROUS', 'short_name' => 'GLA'],
            ['name' => 'GOLA', 'short_name' => 'GOL'],
            ['name' => 'GOLDI', 'short_name' => 'GOI'],
            ['name' => 'GORDON & BROS', 'short_name' => 'GOR'],
            ['name' => 'GRENDHA', 'short_name' => 'GRN'],
            ['name' => 'GUESS', 'short_name' => 'GUE'],
            ['name' => 'GYMPHLEX', 'short_name' => 'GYM'],
            ['name' => 'H.T. BAGS', 'short_name' => 'HTB'],
            ['name' => 'HADLEY', 'short_name' => 'HAD'],
            ['name' => 'HAPPY SOCKS', 'short_name' => 'HAP'],
            ['name' => 'HATLEY', 'short_name' => 'HAT'],
            ['name' => 'HAVAIANAS', 'short_name' => 'HAV'],
            ['name' => 'HEAVENLY FEET', 'short_name' => 'HEA'],
            ['name' => 'HERSCHEL', 'short_name' => 'HER'],
            ['name' => 'HOFF', 'short_name' => 'HOF'],
            ['name' => 'HOOCH', 'short_name' => 'HOO'],
            ['name' => 'HUDSON', 'short_name' => 'HUD'],
            ['name' => 'HUF', 'short_name' => 'HUF'],
            ['name' => 'HUMMEL', 'short_name' => 'HUM'],
            ['name' => 'HUNTER', 'short_name' => 'HUN'],
            ['name' => 'HUSH PUPPIES', 'short_name' => 'HUS'],
            ['name' => 'HX LONDON', 'short_name' => 'HX'],
            ['name' => 'HYPE', 'short_name' => 'HYP'],
            ['name' => 'IKON', 'short_name' => 'IKO'],
            ['name' => 'IMASCHI', 'short_name' => 'IMA'],
            ['name' => 'INDIGO', 'short_name' => 'IND'],
            ['name' => 'INFLUENCE', 'short_name' => 'INF'],
            ['name' => 'INWEAR', 'short_name' => 'INW'],
            ['name' => 'IPANEMA', 'short_name' => 'IPA'],
            ['name' => 'IRON FIST', 'short_name' => 'IRO'],
            ['name' => 'IRREGULAR CHOICE', 'short_name' => 'IRR'],
            ['name' => 'J SHOES', 'short_name' => 'JSH'],
            ['name' => 'J.L.E.', 'short_name' => 'JLE'],
            ['name' => 'JACK WOLFSKIN', 'short_name' => 'JAW'],
            ['name' => 'JANSPORT', 'short_name' => 'JAN'],
            ['name' => 'JERZEES', 'short_name' => 'JER'],
            ['name' => 'JLA', 'short_name' => 'JLA'],
            ['name' => 'JOCKEY', 'short_name' => 'JOC '],
            ['name' => 'JUMPO', 'short_name' => 'JUM'],
            ['name' => 'K-SWISS', 'short_name' => 'KSW'],
            ['name' => 'K.D.K LONDON', 'short_name' => 'KDK'],
            ['name' => 'K.R', 'short_name' => 'KR'],
            ['name' => 'KANGAROOS', 'short_name' => 'KAN'],
            ['name' => 'KANNA', 'short_name' => 'KNN'],
            ['name' => 'KARHU', 'short_name' => 'KAR'],
            ['name' => 'KATE SPADE NEW YORK', 'short_name' => 'KAT'],
            ['name' => 'KAVU', 'short_name' => 'KAV'],
            ['name' => 'KELSI', 'short_name' => 'KEL'],
            ['name' => 'KICKERS', 'short_name' => 'KIC'],
            ['name' => 'KOKO', 'short_name' => 'KOK'],
            ['name' => 'KICKERS', 'short_name' => 'KIC'],
            ['name' => 'KUKRI', 'short_name' => 'KUK'],
            ['name' => 'KULAR', 'short_name' => 'KUL'],
            ['name' => 'LACE & BEADS', 'short_name' => 'LCE'],
            ['name' => 'LACOSTE', 'short_name' => 'LAC'],
            ['name' => 'LAMBRETTA', 'short_name' => 'LAM'],
            ['name' => 'LAVISH ALICE', 'short_name' => 'LAV'],
            ['name' => 'LEE', 'short_name' => 'LEE'],
            ['name' => 'LELLI KELLY', 'short_name' => 'LEL'],
            ['name' => 'LEVIS', 'short_name' => 'LEV'],
            ['name' => 'LITTLE MISTRESS', 'short_name' => 'LIT'],
            ['name' => 'LLOYD AND PRICE', 'short_name' => 'LLO'],
            ['name' => 'LOAKE', 'short_name' => 'LOA'],
            ['name' => 'LOTUS', 'short_name' => 'LOT'],
            ['name' => 'LYDC', 'short_name' => 'LYD'],
            ['name' => 'LYLE & SCOTT', 'short_name' => 'LYL'],
            ['name' => 'MAGEE', 'short_name' => 'MAG'],
            ['name' => 'MAGENTA', 'short_name' => 'MGN'],
            ['name' => 'MAISON SCOTCH', 'short_name' => 'MAI'],
            ['name' => 'MEYER', 'short_name' => 'MEY'],
            ['name' => 'MICHAEL KORS', 'short_name' => 'KOR'],
            ['name' => 'MIPAC', 'short_name' => 'MIP'],
            ['name' => 'MISH MASH', 'short_name' => 'MIS'],
            ['name' => 'MODA IN PELLE', 'short_name' => 'MOD'],
            ['name' => 'MOTEL', 'short_name' => 'MOT'],
            ['name' => 'MUCK', 'short_name' => 'MUC'],
            ['name' => 'MUSTARD', 'short_name' => 'MUS'],
            ['name' => 'NAPAPIJRI', 'short_name' => 'NAP'],
            ['name' => 'NEON ROSE', 'short_name' => 'NEO'],
            ['name' => 'NEW BALANCE', 'short_name' => 'NEW'],
            ['name' => 'NEW ERA', 'short_name' => 'NEE'],
            ['name' => 'NICHOLAS DEAKINS', 'short_name' => 'DEA'],
            ['name' => 'NIKE', 'short_name' => 'NIK'],
            ['name' => 'NO DOUBT', 'short_name' => 'NOD'],
            ['name' => 'OBEY', 'short_name' => 'OBE'],
            ['name' => 'ODEON', 'short_name' => 'ODE'],
            ['name' => 'ONITSUKA TIGER', 'short_name' => 'ONI'],
            ['name' => 'ONLY', 'short_name' => 'ONL'],
            ['name' => 'ORIGINAL PENGUIN', 'short_name' => 'ORI'],
            ['name' => 'PARLEZ', 'short_name' => 'PLZ'],
            ['name' => 'PART TWO', 'short_name' => 'PAR'],
            ['name' => 'PASSPORT', 'short_name' => 'PAS'],
            ['name' => 'PAUL SMITH', 'short_name' => 'PAU'],
            ['name' => 'PEPE JEANS', 'short_name' => 'PEP'],
            ['name' => 'PEX', 'short_name' => 'PEX'],
            ['name' => 'PIILGRIM', 'short_name' => 'PII'],
            ['name' => 'PINSTRIPE', 'short_name' => 'PIN'],
            ['name' => 'POD', 'short_name' => 'POD'],
            ['name' => 'POETIC LICENCE', 'short_name' => 'POE'],
            ['name' => 'POLO RALPH LAUREN', 'short_name' => 'POL'],
            ['name' => 'PRETTY GREEN', 'short_name' => 'PRE'],
            ['name' => 'PSYCHO BUNNY', 'short_name' => 'PSY'],
            ['name' => 'PUBLICITE', 'short_name' => 'PUB'],
            ['name' => 'PUMA', 'short_name' => 'PUM'],
            ['name' => 'PYRENEX', 'short_name' => 'PYR'],
            ['name' => 'QUIKSILVER', 'short_name' => 'QUI'],
            ['name' => 'R.M WILLIAMS', 'short_name' => 'WIL'],
            ['name' => 'RAINBOW', 'short_name' => 'RAI'],
            ['name' => 'RAINS', 'short_name' => 'RAN'],
            ['name' => 'RAVEL', 'short_name' => 'RAV'],
            ['name' => 'RED WING', 'short_name' => 'RED'],
            ['name' => 'REFRESH', 'short_name' => 'REF'],
            ['name' => 'REGATTA', 'short_name' => 'REG'],
            ['name' => 'REMUS UOMO', 'short_name' => 'REM'],
            ['name' => 'REPLAY', 'short_name' => 'REP'],
            ['name' => 'RIEKER', 'short_name' => 'RIE'],
            ['name' => 'RIPCURL', 'short_name' => 'RIP'],
            ['name' => 'ROCKET DOG', 'short_name' => 'ROC'],
            ['name' => 'ROXY', 'short_name' => 'ROX'],
            ['name' => 'RUBY SHOO', 'short_name' => 'RUB'],
            ['name' => 'RVCA', 'short_name' => 'RVC'],
            ['name' => 'SAMSOE & SAMSOE', 'short_name' => 'SAM'],
            ['name' => 'SANTA CRUZ', 'short_name' => 'SAN'],
            ['name' => 'SAUCONY', 'short_name' => 'SAU'],
            ['name' => 'SCOTCH AND SODA', 'short_name' => 'SCO'],
            ['name' => 'SECRID', 'short_name' => 'SEC'],
            ['name' => 'SERVICE WORKS', 'short_name' => 'SER'],
            ['name' => 'SKECHERS', 'short_name' => 'SKE'],
            ['name' => 'SKOPES', 'short_name' => 'SKO'],
            ['name' => 'SLOAN MOLYNAUX', 'short_name' => 'SLO'],
            ['name' => 'SOAKED IN LUXURY', 'short_name' => 'SOA'],
            ['name' => 'SOUR SOLUTION', 'short_name' => 'SOU'],
            ['name' => 'STEPTRONIC', 'short_name' => 'STE'],
            ['name' => 'SUPERDRY', 'short_name' => 'SUP'],
            ['name' => 'SUPERGA', 'short_name' => 'SGA'],
            ['name' => 'TAMARIS', 'short_name' => 'TAM'],
            ['name' => 'TED BAKER', 'short_name' => 'TED'],
            ['name' => 'TFNC', 'short_name' => 'TFN'],
            ['name' => 'THE NORTH FACE', 'short_name' => 'NOR'],
            ['name' => 'THRASHER', 'short_name' => 'THR'],
            ['name' => 'TIMBERLAND', 'short_name' => 'TIM'],
            ['name' => 'TIMEX', 'short_name' => 'TIE'],
            ['name' => 'TOMMY HILFIGER', 'short_name' => 'TOM'],
            ['name' => 'TOMS', 'short_name' => 'TMS'],
            ['name' => 'TRAFFIC PEOPLE', 'short_name' => 'TRA'],
            ['name' => 'TRENDYOL', 'short_name' => 'TRE'],
            ['name' => 'TRU FORM', 'short_name' => 'TRA'],
            ['name' => 'TRUTEX', 'short_name' => 'TRX'],
            ['name' => 'UGG', 'short_name' => 'UGG'],
            ['name' => 'UNICOL', 'short_name' => 'UNI'],
            ['name' => 'URBAN JUNK', 'short_name' => 'URB'],
            ['name' => 'UWIN', 'short_name' => 'UWI'],
            ['name' => 'VANS', 'short_name' => 'VAN'],
            ['name' => 'VERO MODA', 'short_name' => 'VER'],
            ['name' => 'VIANNI', 'short_name' => 'VIA'],
            ['name' => 'VICTORIA', 'short_name' => 'VIC'],
            ['name' => 'VOI JEANS', 'short_name' => 'VOI'],
            ['name' => 'WHITES', 'short_name' => 'WHI'],
            ['name' => 'WILLIAM HUNT', 'short_name' => 'WIH'],
            ['name' => 'WKND', 'short_name' => 'WKN'],
            ['name' => 'WRANGLER', 'short_name' => 'WRN'],
            ['name' => 'XTI', 'short_name' => 'XTI'],
            ['name' => 'ZESPA', 'short_name' => 'ZES'],
        ];  
        

        foreach ($brands as $brand) {
            Brand::create($brand);
        }
    }
}
